site_name: Contoso's Module Web Catalogue
theme:
  name: material
  palette:
    scheme: contoso

    # # Palette toggle for light mode
    # - scheme: default
    #   toggle:
    #     icon: material/brightness-7
    #     name: Switch to dark mode

    # # Palette toggle for dark mode
    # - scheme: slate
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - search.suggest
    - navigation.footer
    - content.code.copy

nav:
  - Home: index.md
  - Pattern Modules:
    - AVD Management Plane: ptn-avdManagementPlane.md
  - Resource Modules:
    - Resources:
        - Resource Groups: resources-resourceGroups.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

extra:
  generator: true

plugins:
  - search
