name: Deploy Private Modules Library Components

on:
  push:
    branches:
    - main
    paths:
    - "infrastructure/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
  LOCATION: 'westeurope'
  ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Sign in to Azure
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - uses: azure/arm-deploy@v2
        id: deploy
        name: Deploy Solution components
        with:
          failOnStdErr: false
          deploymentName: Private-Modules-Library-Components-${{ github.run_number }}
          scope: subscription
          subscriptionId: ${{ env.ARM_SUBSCRIPTION_ID }}
          template: infrastructure/deploy.bicep
          parameters: infrastructure/deploy.bicepparam
          region: ${{ env.LOCATION }}
