name: AVD Management Plane Module CI/CD

on:
  push:
    branches:
      - 'feature/*'
      - 'main'
    paths:
      - 'modules/ptn/avdManagementPlane/deploy.bicep' # Trigger only on changes to the specified module path

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
  MODULE_REPO_NAME: 'modules/ptn/avdmanagementplane'
  MODULE_FILE_PATH: 'modules/ptn/avdManagementPlane/deploy.bicep'
  MODULE_VERSION_FILE_PATH: 'modules/ptn/avdManagementPlane/version.json'
  MODULE_REGISTRY_NAME: ${{ vars.AZ_MODULE_REGISTRY }} # Adjust as necessary

jobs:
  lint-and-psrule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: azure/login@v2.1.1
        name: Sign in to Azure
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
      - name: Lint and PSRule Analysis
        uses: ./.github/actions/lint-psrule
        with:
          moduleFilePath: ${{ env.MODULE_FILE_PATH }}
          testFilePath: ${{ env.MODULE_TEST_FILE_PATH }}

  publish-and-update-module:
    needs: lint-and-psrule
    if: github.ref == 'refs/heads/main' # Only run on main branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: azure/login@v2.1.1
        name: Sign in to Azure
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
      - name: Publish Module
        uses: ./.github/actions/publish
        with:
          moduleFilePath: ${{ env.MODULE_FILE_PATH }}
          versionFilePath: ${{ env.MODULE_VERSION_FILE_PATH }}
          repoName: ${{ env.MODULE_REPO_NAME }}
          registryName: ${{ env.MODULE_REGISTRY_NAME }}

  generate-and-update-docs:
    needs: publish-and-update-module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: azure/login@v2.1.1
        name: Sign in to Azure
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Generate and Update Documentation
        uses: ./.github/actions/generate-docs
        with:
          moduleFilePath: ${{ env.MODULE_FILE_PATH }}
          registryName: ${{ env.MODULE_REGISTRY_NAME }}
          repositoryName: ${{ env.MODULE_REPO_NAME }}
          githubSecret: ${{ secrets.PAT_TOKEN }}
